### ISSUE TITLE
Incorrect normals in exported o3d files

### ISSUE THREAD

**Issue by space928** [space928/Blender-O3D-IO-Public#51]
### Describe the bug
In some cases, it appears as if the exported normals of an o3d file are flipped when they shouldn't be. This still needs investigation to be sure. This could be related to o3d transform matrix exporting.

### Screenshots
![image](https://user-images.githubusercontent.com/15130114/233130949-ba79aa9c-c45e-469e-8a6a-2aa994362071.png)

Thomas already has example o3d files to test this with (`C2G_4T_Wagenkasten.o3d`)

**Comment by space928** [comment]
I think I've fixed this in the latest beta, if anyone wants to test this for me please have a go:
https://github.com/space928/Blender-O3D-IO-Public/releases/tag/v1.2.1b

**Comment by KCR58Game** [comment]
> I think I've fixed this in the latest beta, if anyone wants to test this for me please have a go: https://github.com/space928/Blender-O3D-IO-Public/releases/tag/v1.2.1b

I tested it and the problem listed in this post and [#69](https://github.com/space928/Blender-O3D-IO-Public/issues/69) still exist.

**Comment by space928** [comment]
Please try the latest build, it should be fixed:
https://github.com/space928/Blender-O3D-IO-Public/releases/tag/v1.1.2b-1

**Comment by space928** [comment]
*Note to myself*
I thought I had fixed this (for like the fifth time at this point), turns out I still haven't... 😤


![Image](https://github.com/space928/Blender-O3D-IO-Public/assets/15130114/10046986-d6f6-49f2-be39-6d1003bb5e94)

See Haus03a.sco in `OMSI 2\Sceneryobjects\Buildings_RUE\`

**Comment by space928** [comment]
If this isn't fully fixed before release, I'll just make the importer default to not importing custom normals, and daring people can try to import custom normals, in many cases it does work.

**Comment by lmaodick1239** [comment]
no you are still not ready

![Image](https://github.com/space928/Blender-O3D-IO-Public/assets/67418738/d239dc8c-3681-49b2-b485-4c9e3b9400fa)
